### ISSUE TITLE
Release 2.1.17

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1013]
On the docket:
+ [x] TypeError when resolving local platforms. #1043
+ [x] No such file for interpreter's binary name #1009
+ [x] Pex resources leak while bootstrapping pants #1050
+ [x] Pex PEX perf regression #1054

**Comment by thamenato** [comment]
hey @jsirois is there any way that I can already get a "bleeding-edge" version with #1009 ? Just wondering so I can go back into migrating to pants v2.

**Comment by Eric-Arellano** [comment]
We might want to cut this Pex release early so that we can do a Pants release this weekend. Thoughts, John?

**Comment by jsirois** [comment]
Sounds good. I need to document and fix a perf regression 1st though that I've been working on.
