### ISSUE TITLE
Release 2.1.18

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1053]
On the docket:
+ [x] Control of the TMPDIR used by Pex and its subprocesses (notably Pip). #1067
+ [x] Add Python 3.9 support. #1064
+ [x] pex creation fails under pants w/ `No such file or directory` error #1051 
+ [x] Pex fails to consistently use https_proxy + --cert #1058
+ [x] Honor `sys.executable` unless macOS Framework. #1065

**Comment by jsirois** [comment]
I broke out 2.1.19 in #1069 to take care of the rest. In particular #1031 which is a bit risky / large.
