### ISSUE TITLE
Release 2.1.19

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1069]
On the docket:
+ [x] Allow constraining the interpreter search path directly. #1020
+ [x] Pex should validate the PEX_INHERIT_PATH option and fail fast. #921
+ [x] Remove `--use-first-matching-interpreter` misfeature. #1076
