### ISSUE TITLE
Release 2.1.21

### ISSUE THREAD

**Issue by Eric-Arellano** [pantsbuild/pex#1078]
On the docket:
+ [x] "FileNotFoundError: [Errno 2] No such file or directory" in pex #1098
+ [x] Unclosed resource warning for `/dev/null` in PEX teardown. #1101
+ [x] Remove `--sources-directory` / `--resources-directory` distinction. #1100
+ [x] Invalid requirement, parse error at "'python_v' #940
+ [x] Pex skipping pandas activation #1017
+ [x] Changing vendored versions does not fully clean up previous version #1096
+ [x] Pex discards the current interpreter's PATH entry when it is a directory entry. #1109

**Comment by jsirois** [comment]
Broke out remaining issues to Release 2.1.21 in #1111. This release has enough including a few fixes desirable for Pants 2.{0,1}.
