### ISSUE TITLE
Release 2.1.20

### ISSUE THREAD

**Issue by Eric-Arellano** [pantsbuild/pex#1089]
On the docket:

+ [x] Fix `dir_hash` vs. bytecode compilation races. #1080
+ [x] Fix `--pex-python` when it's the same as the current interpreter. #1087
+ [x] Prefer more recent patch versions in interpreter discovery. #1088
+ [x] Fix readthedocs doc generation. #1081
