### ISSUE TITLE
Release 2.1.22

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1111]
On the docket:
+ [x] Fix `--help-variables` docs. #1113
+ [x] pex binary hangs on startup at atomic_directory #1119
+ [x] pex vendoring does not (always) isolate itself from a colliding setuptools install in site-packages #1031
+ [x] Remove long deprecated support for _pex module. #1135

**Comment by jsirois** [comment]
Truncating this docket over to #1138 to get out this release and 2.1.23 in #1134 with the Pip upgrade to unblock macOS Big Sur users.
