### ISSUE TITLE
Release 2.1.25

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1144]
On the docket:
+ [x] Use symlinks to add dists in the Pex CLI. #1185
+ [x] Support PEX files as resolve repositories. #1108
+ [x] Pex does not use the pip 2020-resolver when resolving for Python 2.7 #1179
+ [x] PexInfo.copy does not copy its collection attributes. #1147
+ [x] Add support for PEX_INTERPRETER `-c`, `-m` and `-` special modes to PEX venvs. #1136
+ [x] Requires-Python handling causes LegacyVersion warning #1150
+ [x] Add option to extend PATH with additional console scripts #1097
+ [x] Removing "activation" time from PEX #1115
+ [x] Run PEXes as normal applications #962
+ [x] Top level environment markers are lost in built PEXes. #899
+ [x] Using `--resolver-version=pip-2020-resolver` yields poor dependency conflict information. #1159

**Comment by jsirois** [comment]
Broke off #1186 to take up the overflow items into 2.1.26 so 2.1.25 is ready for release tomorrow.
