### ISSUE TITLE
Release 2.1.29

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1198]
On the docket:
+ [x] Upgrade to Pip 20.3.4 #1203
+ [x] PexInfo.pex_hash does not include metadata #1218
+ [x] Fix PyPy3 `--venv` mode. #1221

**Comment by jsirois** [comment]
Moved pre-existing items moved off to 2.1.30 in #1204.
