### ISSUE TITLE
Release 2.1.31

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1226]
On the docket:
+ [x] When Pex is run from a Pex PEX its isolation is broken. #1232
+ [x] The `--venv` mode `pex` script does not have a `__name__ == '__main__'` guard breaking multiprocessing. #1236
+ [x] The `--seed` mode for a `--venv` PEX is unsafe. #1239
+ [x] The venv `pex` script handles entrypoint functions differently from PEX. #1241
+ [x] Interpreter identification leaks an unconstrained `$PWD` entry into `sys.path`. #1231
+ [x] Support control of venv creation mode `--copies` vs. `--symlinks` #1230

**Comment by jsirois** [comment]
Maybes moved over to 2.1.32 in #1237.
