### ISSUE TITLE
Release 2.1.33

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1253]
On the docket:
+ [x] Support console scripts found in the PEX_PATH. #1257
+ [x] Fix Requires metadata handling. #1262
+ [x] Fix PEX file reproducibility. #1259
+ [x] Fix venv script shebang rewriting. #1260
+ [x] Introduce the repository PEX_TOOL. #1256)
