### ISSUE TITLE
Release 2.1.34

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1263]
On the docket:
+ [x] Allow command-line arguments to be read from a file #1271
+ [x] Issue when running a module inside pex file #1018
+ [x] Guard against concurrent re-imports. #1270
+ [x] Ensure Pip logs to stderr. #1268

**Comment by jsirois** [comment]
Moved from Release 2.1.33 in #1253 to make way for a hotfix for #1201.
