### ISSUE TITLE
Release 2.1.35

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1269]
On the docket:
+ [x] Ensure venv pex does not enter a re-exec loop. #1286
+ [x]  Improve resolve error information. #1287 
+ [x] Expose Pex tools via a pex-tools console script. #1279
+ [x] Fix auto-created `--venv` core scripts. (#1278)

**Comment by jsirois** [comment]
Moved from Release 2.1.34 in #1263 to make way for a hotfix for #1267.
