### ISSUE TITLE
Release 2.1.36

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1283]
On the docket:
+ [x] Add support for --seed verbose. #1299
+ [x] PEXBuilder symlinked wheel install chroots can observe compilation. #1297
+ [x] Pex builds wheels with bad platform tags on some mac machines. #1294

**Comment by jsirois** [comment]
Forked off from Release 2.1.35 #1269.
