### ISSUE TITLE
Release 2.1.43

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1340]
On the docket:
+ [x] Support more verbose output for interpreter info. (#1347) 
+ [x] Fix Pex emitting warnings about its Pip PEX venv. (#1351)
+ [x] Fix execution modes. (#1353) 
+ [x] Warn for PEX env vars unsupported by venv. (#1354)
+ [x] Do not suppress pex output in bidst_pex (#1358)
+ [x] Using --platform manylinux2010 includes pyarrow wheel for manylinux2014 #1355
+ [x] Fix --no-manylinux. #1365
+ [x] Environment markers are incorrectly evaluated for --platform resolves. #1366
+ [x] Pex probes wheel metadata incorrectly. #1375

**Comment by jsirois** [comment]
Moved from Release 2.1.42 #1333 to make way for a bugfixes for #1336 and #1337.
