### ISSUE TITLE
Release 2.1.46

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1397]
On the docket:
+ [x] Fix Pip proprietary URL env marker handling. #1417 
+ [x] Un-reify installed wheel script shebangs. #1410
+ [x] Support deterministic repository extract tool. #1411
+ [x] support setuptools scripts #1379

**Comment by jsirois** [comment]
Split off from "Release 2.1.45 #1389" to make way for the #1396 bdist_all fix.
