### ISSUE TITLE
Release 2.1.52

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1481]
On the docket:
+ [ ] PEX_INHERIT_PATH+default shebangs don't interact well with virtualenvs #1344
+ [ ] Pex interpreter cache is not upgrade / downgrade safe. #1176
+ [ ] Decouple PEX runtime interpreter selection from buildtime interpreter selection. #1020
+ [ ] Provide a better resolve error message for a Platform DistributionTarget when `--resolve-local-platforms`. #1070
+ [ ] Remove `PEX_PYTHON_PATH` from build time interpreter selection. #1075

**Comment by jsirois** [comment]
Split off from "Release 2.1.51 #1449" to make way for a fix for #1479.
