### ISSUE TITLE
Release 2.1.55

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1506]
On the docket:
+ [x] Add official support for Python 3.10 (#1512)
+ [x] Always register global options. (#1511)
+ [x] Fix RTD generation by pinning docutils low. (#1509)

**Comment by jsirois** [comment]
Split off from "Release 2.1.54 #1501" to make way for a fix for #1504 in #1505.
