### ISSUE TITLE
Release 2.1.57

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1522]
On the docket:
+ [ ] Do not re-hash installed wheels. (#1534)
+ [ ] Improve space efficiency of `--venv` mode. (#1532)
+ [ ] Add venv `--remove {pex,all}` option. (#1525)

**Comment by jsirois** [comment]
Split off from "Release 2.1.56 #1515" to make way for a fix for wheel install hermeticity (#1521).
