### ISSUE TITLE
Release 2.1.66

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1592]
On the docket:
+ [x] Support specifying foreign platforms in full detail. #1597
+ [x]  Respect PEX_ROOT in PEXEnvironment.mount. #1599 
+ [x]  Be able to see what .pex file is run from the list of system processes #1604

**Comment by jsirois** [comment]
Split off from "Release 2.1.65 #1588" to make way for a vendored packaging & wheel upgrade with a patch that brings mac universal2 wheel support.
