### ISSUE TITLE
Release 2.1.72

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1663]
On the docket:
+ [x] Fix Locker to prune un-downloaded entries. (#1666)
+ [x] Fix venv creation to ignore ambient PEX env vars. #1669
+ [ ] Lockfiles: requirement might not be compatible with requested interpreter constraints #1667

**Comment by jsirois** [comment]
Split off from "Release 2.1.71 #1642" to make way for a fix for `--venv` handling of RECORDs (#1656).
