### ISSUE TITLE
Release 2.1.73

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1670]
On the docket:
+ [x] Unexpected distribution hash #1683 
+ [x] Pex fails to parse wheel tags correctly when resolving from a lock. #1676 
+ [x] `pex3 lock create --style universal` does not fully patch ambient interpreter properties. #1681
