### ISSUE TITLE
Release 2.1.80

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1718]
On the docket:
+ [ ] ...

Maybe:
+ [ ] Decouple PEX runtime interpreter selection from buildtime interpreter selection. #1020

Unlikely / backlog:
+ [ ] PEX_INHERIT_PATH+default shebangs don't interact well with virtualenvs #1344
+ [ ] Pex interpreter cache is not upgrade / downgrade safe. #1176
+ [ ] Provide a better resolve error message for a Platform DistributionTarget when `--resolve-local-platforms`. #1070
+ [ ] Remove `PEX_PYTHON_PATH` from build time interpreter selection. #1075
