### ISSUE TITLE
Release 2.1.93

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1793]
On the docket:
+ [x] Support adding new requirements in a lock update. (#1797)
+ [x] Add `pex3 lock update --dry-run check` mode. (#1799)
+ [x] Universal locks no longer record a `platform_tag`. (#1800)
+ [x] Support python script file executable. (#1807)
+ [x] Fix PEX scrubbing to account for sys.excepthook. #1810
+ [x] zipapp mode drops tail log lines #1802 
+ [x] Surface pip download logging. #1808
+ [x] Use pip download instead or URLFetcher. #1811
