### ISSUE TITLE
Release 2.1.97

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1835]
On the docket:
+ [ ] ...

Unlikely / backlog:
+ [ ] PEX_INHERIT_PATH+default shebangs don't interact well with virtualenvs #1344
+ [ ] Pex interpreter cache is not upgrade / downgrade safe. #1176
+ [ ] Provide a better resolve error message for a Platform DistributionTarget when `--resolve-local-platforms`. #1070
+ [ ] Remove `PEX_PYTHON_PATH` from build time interpreter selection. #1075

**Comment by jsirois** [comment]
Moved from "Release 2.1.96 #1822" to clear space for the Pip upgrade.
