### ISSUE TITLE
Release 2.1.98

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1840]
On the docket:
+ [x] Tags should be patched for --platform. #1846
+ [x] PEXes should be useable as sys.path entries. #1839
+ [ ] Pex lock downloads fail for foreign platforms. #1849

**Comment by jsirois** [comment]
Moved from "Release 2.1.97 #1835" to clear space for the Pip upgrade.
