### ISSUE TITLE
Release 2.1.102

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1862]
On the docket:
+ [x] pex 2.1.101 issue: virtualenv is not valid #1866
+ [x] `--inherit-path {prefer,fallback}` does not work but `PEX_INHERIT_PATH={prefer,fallback}` does. #1870
+ [x] Error using pex + virtualenv >=20.0.0 + python 2.7 #992

**Comment by jsirois** [comment]
Split off from "Release 2.1.101 #1857" to make way for a fix for #1861.
