### ISSUE TITLE
Release 2.1.104

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1873]
On the docket:
+ [x] Pull in Pip fixes. #1805
+ [x] pex fails to overwrite zipapp pex with loose pex #1879
+ [x] Make lock update sensitive to artifacts. #1887 
+ [x] PEXBuilder is not robust to ephemeral .pyc compiles. #1889

Unlikely / backlog:
+ [ ] PEX_INHERIT_PATH+default shebangs don't interact well with virtualenvs #1344
+ [ ] Pex interpreter cache is not upgrade / downgrade safe. #1176
+ [ ] Provide a better resolve error message for a Platform DistributionTarget when `--resolve-local-platforms`. #1070
+ [ ] Remove `PEX_PYTHON_PATH` from build time interpreter selection. #1075

**Comment by jsirois** [comment]
Broken off from "Release 2.1.103 #1868" to make way for a fix for #1872.
