### ISSUE TITLE
Release 2.1.120

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#2012]
On the docket:
+ [x] Support REPL command history #2019 
+ [ ] Using --complete-platform with --resolve-local-platforms should build sdists when local platform provides a subset of complete-platforms #2026
+ [ ] A loose layout, venv-with-symlink PEX creates brittle symlinks #2023

**Comment by jsirois** [comment]
Moved from "Release 2.1.119 #2008" to make way for #2002.
