### ISSUE TITLE
Release 2.1.122

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#2040]
On the docket:
+ [x] Support the latest Pip releases: 22.3.1 & 23.0 #2056
+ [x] Lock sdists with prepare-metadata-for-build-wheel. #2053
+ [x] Fix `execute_parallel` "leaking" a thread. #2052

**Comment by jsirois** [comment]
Moved from "Release 2.1.121 #2032" to make way for a few Poetry interoperability fixes.
