### ISSUE TITLE
Release 2.1.123

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#2054]
On the docket:
+ [x] Create lockfile for xmlsec fails #2063
+ [x] Internal not enough values to unpack error for pex3 lock create 'pip @ https://github.com/pypa/pip/archive/22.0.2.zip' ... #2057
+ [x] Pex lock creation does not handle wheels with non {cp,pp,py} pyver tag. #2059

**Comment by jsirois** [comment]
Moved from "Release 2.1.122 #2040" to make way for a posix file locking bug fix and a fix to allow more classes of lock to succeed.
