### ISSUE TITLE
Release 2.1.124

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#2058]
On the docket:
+ [x] Pex files do not allow for OpenTelemetry auto-instrumentation #2065
+ [x] Intermittent / nondeterministic failure building `requirements.pex` due to missing `site-packages` #2066
+ [ ] Add support for Pip 23.0.1. #2072

**Comment by jsirois** [comment]
Broken off of "Release 2.1.123 #2054" to make way for a fix for #2057.
