### ISSUE TITLE
Release 2.1.135

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#2126]
On the docket:
+ [x] Add Support for Pip 23.1.1. #2133
+ [x] Introduce pex3 venv inspect. #2135
+ [x] Add support for Pip 23.1.2. #2142
+ [ ] Introduce pex3 venv create. #2140

**Comment by jsirois** [comment]
Broken off of "Release 2.1.134 #2121" to make way for a fix for #2125.
