### ISSUE TITLE
Release 1.6.2

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#652]
On the docket:
+ [X] pex 1.6.1 cannot build cryptography 2.5 #661
+ [x] Allow pex to be invoked using runpy (python -m pex). #637 
+ [x] Add User-Agent header when resolving via urllib #663

**Comment by jsirois** [comment]
1.6.2 is released:
+ https://pypi.org/project/pex/1.6.2/#files
+ https://github.com/pantsbuild/pex/releases/tag/v1.6.2
