### ISSUE TITLE
Release 1.6.4

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#681]
On the docket:
+ [x] Restore pex.pex_bootstrapper.is_compressed API #684
+ [ ] Release more flexible pex binaries. #654
  + [x] If an `--interpreter-constraint` is set, it should always be honored. #656

**Comment by jsirois** [comment]
I've short-cycled this in the interests of getting https://github.com/pantsbuild/pants/pull/7186 green - outstanding docket items moved to release 1.6.5 tracked in #690.
