### ISSUE TITLE
Release 1.6.7

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#704]
On the docket:
+ [x] Fix pex file loses the executable permissions of binary files #703
+ [x] When iterating over Zipfiles, always use the Unix file separator to fix a Windows issue #638
+ [x] Make a copy of globals() before updating it. #715
+ [x] Add timeout when using requests. #726
+ [x] Introduce new `--no-compile` flag to not include .pyc in built pex due to its non-determinism #718 
+ [x] Add new `--no-use-system-time` flag to use a deterministic timestamp in built PEX #722
+ [x] Fix PexInfo requirements using a non-deterministic data structure #723
+ [x] Fix reproducible build test improperly using the -c flag and add a new test for -c #725
+ [x] Fix reproducible builds sdist test by properly requiring building the wheel #727
+ [x] Add delayed pkg_resources import fix from #713, with an integration test #730

Deferred:
+ [ ] Remove PEX_HTTP_RETRIES and push into a flag for the pex tool #94

**Comment by jsirois** [comment]
Pants will want to consume this release and undo hacks introduced by https://github.com/pantsbuild/pants/pull/7659 fixed in #726.

**Comment by stuhood** [comment]
Tagged and away: https://travis-ci.org/pantsbuild/pex/builds/532103661

**Comment by stuhood** [comment]
Released https://pypi.org/project/pex/1.6.7/

Needed one post-merge-commit fix for the changelog (https://github.com/pantsbuild/pex/commit/bafa4bb483cb54f60ca4a45615fef37898817c7a), which has seemingly been broken for a while.
