### ISSUE TITLE
Release 1.6.8

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#740]
On the docket:

+ [x] Fixup pex re-exec during bootstrap. #741 
  + [x] Pex should not re-exec when the current interpreter satifies constraints #709
  + [x] Pex should not lose PEX_PYTHON or PEX_PYTHON_PATH when re-exec-ing #710
+ [x] Fix resolution of `setup.py` project extras. #739

Deferred:

+ [ ] Remove PEX_HTTP_RETRIES and push into a flag for the pex tool #94
+ [ ] Sdist resolution is not always reproducible #735

**Comment by jsirois** [comment]
Released:
+ https://pypi.org/project/pex/1.6.8
+ https://github.com/pantsbuild/pex/releases/tag/v1.6.8
