### ISSUE TITLE
Release 1.6.9

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#751]
On the docket:
+ [x] Fix pkg resource early import #750
+ [x] Fix `sys.path` scrubbing of pex extras modules. #752

Maybe on the docket:
+ [ ] Problem running PEX files with restricted permissions #746
