### ISSUE TITLE
Release 2.0.2

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#800]
On the docket:

+ [x] Add a test of pypi index rendering. (#799)
+ [x] Fix `iter_compatible_interpreters` path biasing. (#798)
+ [x] Fix current platform handling. #801
