### ISSUE TITLE
Release 2.0.3

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#814]
On the docket:

+ [x] Pex should trust any host passed via `--index` or `--find-links`. #812
+ [x] A cache should always be used by `pex.resolver.resolve`. #809
+ [x] Use the resolve cache to skip installs. #815
+ [x] Parallelize resolve. #818
+ [x] Cache sdist & local project builds #817
+ [ ] Unify resolve and runtime wheel caches. #820
