### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#837]
On the docket:

The prime motivator:
+ [x] Pex does not download foreign abi3 wheels correctly #823

Changes to support the above as well as others:
+ [x] Fix pex resolving for foreign platforms. #835  
+ [x] Use pypa/packaging. #831
+ [x] Upgrade vendored setuptools to 42.0.2. #832
+ [x] De-vendor pex just once per version. #833
+ [x] Support VCS urls for vendoring. #834
+ [x] Support python 3.8 in CI. #829
+ [x] Fix pex resolution to respect --ignore-errors. #828
+ [x] Kill `pkg_resources` finders monkey-patching. #827
+ [x] Use flit to distribute pex. #826
+ [x] Cleanup extras_require. #825
