### ISSUE TITLE
Release 2.1.1

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#857]
On the docket:
+ [x] PEX 2.1.0 regression: pex file won't build inside a running docker image as user #850
+ [x] Fully pin vendored requirements. #853
+ [x] Fix `tox -epackage` to create pex supporting 3.8. #843
+ [x] Pex erroneously warns about needing to use vendored `pkg_resources` for distributions with empty `namespace_packages.txt` metadata files. #840
+ [x] Interpreter discovery and pyenv don't interact well #782
+ [x] ensure_python_interpreter() bootstrapping broken on pypy shard #477
+ [x] Resolve error checking does not account for environment markers. #851
+ [x] Ensure Pex PEX contraints match pex wheel / sdist. #863
