### ISSUE TITLE
Release 2.1.7

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#909]
On the docket:
+ [x] Top level requirements in PEX-INFO are missing needed environment markers. #898
+ [x] Improve error message when interpreters cannot be found #922
+ [x] Adding `--runtime-pex-root` option. #780
+ [x] The pex cache (PEX_ROOT) is not always controllable. #926
+ [x] Consider passing through `PEX_` env vars to PEXed Pex. #925
+ [x] Preserve PEX_ env variables after calling pex #180

**Comment by jsirois** [comment]
Broken off from #902

**Comment by jsirois** [comment]
Moved "Top level environment markers are lost in built PEXes." (#899) to Release 2.1.8 (#933).
