### ISSUE TITLE
Release 2.1.8

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#933]
On the docket:
+ [x] Cache pip.pex. #937
+ [x] Ensure the interpreter path is a file #938
+ [x] Support an unzip toggle for PEXes. #939
+ [x] Better support unzip mode PEXes. #941

**Comment by jsirois** [comment]
"Top level environment markers are lost in built PEXes." (#899) is now moved to the 2.1.9 release tracked in #944.
