### ISSUE TITLE
Release 2.1.10

### ISSUE THREAD

**Issue by benjyw** [pantsbuild/pex#950]
On the docket:
+ [x] Improve Pex packaging. (#961)
+ [x] Make the interpreter cache deterministic. (#960)
+ [x] Fix deprecation warning for `rU` mode (#956)
+ [x] Fix runtime resolve error message generation. (#955)
+ [x] Kill dead code. (#954)
+ [x] Many Pex tests fail under Python 2.7 in CI #967
+ [x] Add a `--local` mode for packaging the Pex PEX. #971
+ [x] Split Pex resolve API. (#970)
+ [x] Can't run PEX file when a dependency's wheel includes a build tag #964
+ [ ] Expose network configuration in pex options. #803

**Comment by benjyw** [comment]
On the docket:
+ [ ] Top level environment markers are lost in built PEXes. #899
+ [ ] Requirement resolution errors should provide enough information to resolve conflicts. #943
