### ISSUE TITLE
Release 2.1.13

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#972]
On the docket:
+ [x] vendored pip prompts for user input #983
+ [x] Add support for satisfying `--platform=X` with a local interpreter iff one is found. #996
+ [x] Feature Request : Syntax for --platform to refer to the current platform #997
